repos:
  - repo: local
    hooks:
      - id: rubocop
        name: RuboCop
        entry: bundle exec rubocop
        language: ruby
        types: [ruby]
        exclude: ^db/schema\.rb$

      - id: rails-test
        name: Rails Test
        entry: bundle exec rails test
        language: system
        pass_filenames: false
